import bcrypt from 'bcryptjs';
import User from '../models/User.js';
import Application from '../models/Application.js';
import Member from '../models/Member.js';
import Event from '../models/Event.js';
import { getDbStatus } from '../config/db.js';

// Pre-seeded in-memory store for autonomous operation
export const inMemoryStore = {
  users: [
    {
      _id: 'user_admin_001',
      id: 'user_admin_001',
      name: 'Dr. Faculty Admin / Core Council',
      email: 'admin@csivcet.org',
      password: '', // will be hashed upon initialization
      plainPassword: 'CsiVcet@2026',
      role: 'admin',
      chapterDesignation: 'CSI VCET Chapter Lead Administrator',
      createdAt: new Date().toISOString(),
    },
  ],
  applications: [
    {
      _id: 'app_001',
      id: 'app_001',
      name: 'Ronit Sharma',
      email: 'ronit.sharma@vcet.edu.in',
      phone: '+91 98201 12345',
      rollNumber: '24CMP042',
      year: 'SE',
      department: 'Computer Engineering',
      domainPreference: 'Technical',
      skills: ['React', 'Node.js', 'Python', 'Git'],
      statementOfPurpose: 'Passionate about full-stack web development and excited to contribute to CSI VCET technical hackathons and peer mentoring.',
      portfolioUrl: 'https://github.com/ronit-sharma',
      status: 'Accepted',
      interviewSlot: '2026-10-12 11:30 AM',
      adminNotes: 'Strong React fundamentals, cleared live coding challenge with top rank.',
      dateApplied: new Date(Date.now() - 4 * 86400000).toISOString(),
    },
    {
      _id: 'app_002',
      id: 'app_002',
      name: 'Priya Nair',
      email: 'priya.nair@vcet.edu.in',
      phone: '+91 98334 54321',
      rollNumber: '23IT019',
      year: 'TE',
      department: 'Information Technology',
      domainPreference: 'Web & App',
      skills: ['TypeScript', 'Next.js', 'Tailwind CSS', 'Figma'],
      statementOfPurpose: 'Lead frontend architect for departmental project; want to build impactful portals for college technical festivals.',
      portfolioUrl: 'https://priyanair.dev',
      status: 'Interviewed',
      interviewSlot: '2026-10-08 02:00 PM',
      adminNotes: 'Excellent UI/UX eye and design system experience. Second round pending with Tech Head.',
      dateApplied: new Date(Date.now() - 3 * 86400000).toISOString(),
    },
    {
      _id: 'app_003',
      id: 'app_003',
      name: 'Ananya Kulkarni',
      email: 'ananya.kulkarni@vcet.edu.in',
      phone: '+91 99200 67890',
      rollNumber: '25AID012',
      year: 'FE',
      department: 'Artificial Intelligence & Data Science',
      domainPreference: 'Technical',
      skills: ['Python', 'Data Structures', 'C++', 'SQL'],
      statementOfPurpose: 'First year student eager to learn enterprise software development and volunteer in AI workshops organized by CSI.',
      portfolioUrl: 'https://github.com/ananyakulkarni',
      status: 'Pending',
      interviewSlot: null,
      adminNotes: '',
      dateApplied: new Date(Date.now() - 2 * 86400000).toISOString(),
    },
    {
      _id: 'app_004',
      id: 'app_004',
      name: 'Tanmay Patil',
      email: 'tanmay.patil@vcet.edu.in',
      phone: '+91 97654 32109',
      rollNumber: '24CMP088',
      year: 'SE',
      department: 'Computer Engineering',
      domainPreference: 'Event Management',
      skills: ['Public Speaking', 'Event Logistics', 'Sponsorship Outreach'],
      statementOfPurpose: 'Handled technical symposium logistics in first year; eager to manage HackVCET 2026 operations and national attendee liaison.',
      portfolioUrl: '',
      status: 'Pending',
      interviewSlot: null,
      adminNotes: 'Prior experience in inter-collegiate fest logistics.',
      dateApplied: new Date(Date.now() - 1 * 86400000).toISOString(),
    },
    {
      _id: 'app_005',
      id: 'app_005',
      name: 'Sahil Mehta',
      email: 'sahil.mehta@vcet.edu.in',
      phone: '+91 98111 22334',
      rollNumber: '23EXTC05',
      year: 'TE',
      department: 'Electronics & Telecommunication',
      domainPreference: 'Sponsorship',
      skills: ['Negotiation', 'Pitch Decks', 'Canva'],
      statementOfPurpose: 'Seeking to bridge industry sponsors with VCET tech fests.',
      portfolioUrl: '',
      status: 'Declined',
      interviewSlot: null,
      adminNotes: 'Applicant accepted an alternative internship conflicting with mandatory chapter hours.',
      dateApplied: new Date(Date.now() - 6 * 86400000).toISOString(),
    },
    {
      _id: 'app_006',
      id: 'app_006',
      name: 'Sneha Desai',
      email: 'sneha.desai@vcet.edu.in',
      phone: '+91 98700 99887',
      rollNumber: '24IT033',
      year: 'SE',
      department: 'Information Technology',
      domainPreference: 'Creatives & Design',
      skills: ['Figma', 'Illustrator', 'Video Editing', 'After Effects'],
      statementOfPurpose: 'Created branding kits for college clubs; looking forward to spearheading CSI VCET digital media campaigns.',
      portfolioUrl: 'https://behance.net/snehadesai',
      status: 'Accepted',
      interviewSlot: '2026-10-14 10:00 AM',
      adminNotes: 'Outstanding visual portfolio and typography skills. Approved for Design Lead position.',
      dateApplied: new Date(Date.now() - 5 * 86400000).toISOString(),
    },
    {
      _id: 'app_007',
      id: 'app_007',
      name: 'Aditya Joshi',
      email: 'aditya.joshi@vcet.edu.in',
      phone: '+91 91234 56789',
      rollNumber: '25CMP018',
      year: 'FE',
      department: 'Computer Engineering',
      domainPreference: 'Web & App',
      skills: ['HTML5', 'CSS3', 'JavaScript', 'Tailwind'],
      statementOfPurpose: 'Keen to join the CSI web committee to learn backend development and contribute to chapter open-source repositories.',
      portfolioUrl: 'https://github.com/adityajoshi-dev',
      status: 'Interviewed',
      interviewSlot: '2026-10-10 03:30 PM',
      adminNotes: 'Good understanding of frontend basics, scheduled for follow-up code review.',
      dateApplied: new Date(Date.now() - 1 * 86400000).toISOString(),
    },
    {
      _id: 'app_008',
      id: 'app_008',
      name: 'Pooja Varma',
      email: 'pooja.varma@vcet.edu.in',
      phone: '+91 99887 76655',
      rollNumber: '23AID045',
      year: 'TE',
      department: 'Artificial Intelligence & Data Science',
      domainPreference: 'Technical',
      skills: ['PyTorch', 'TensorFlow', 'FastAPI', 'Docker'],
      statementOfPurpose: 'Interested in mentoring students on Machine Learning and leading workshop sessions on Generative AI applications.',
      portfolioUrl: 'https://github.com/poojavarma-ml',
      status: 'Accepted',
      interviewSlot: '2026-10-11 04:00 PM',
      adminNotes: 'Strong ML research background, published paper in IEEE student conference.',
      dateApplied: new Date(Date.now() - 7 * 86400000).toISOString(),
    },
  ],
  members: [
    // Faculty Coordinators (Featuring Bollywood & Avengers Star Avatars)
    {
      _id: 'mem_fac_01',
      id: 'mem_fac_01',
      name: 'Dr. Swati Varma',
      role: 'Faculty Coordinator (Computer Engg.)',
      category: 'Faculty Coordinators',
      department: 'Computer Engineering',
      year: 'Faculty',
      email: 'swati.varma@vcet.edu.in',
      phone: '+91 9869775463',
      imageUrl: '/actors/deepika.jpg',
      starAvatar: 'Deepika Padukone (Bollywood)',
      bio: 'Associate Professor & Faculty Coordinator for CSI VCET Chapter, Department of Computer Engineering.',
      priorityOrder: 1,
    },
    {
      _id: 'mem_fac_02',
      id: 'mem_fac_02',
      name: 'Ms. Maya Varghese',
      role: 'Faculty Coordinator (CSE-DS)',
      category: 'Faculty Coordinators',
      department: 'Computer Science & Engineering (Data Science)',
      year: 'Faculty',
      email: 'maya.varghese@vcet.edu.in',
      phone: '+91 9699547709',
      imageUrl: '/actors/elizabeth_olsen.jpg',
      starAvatar: 'Elizabeth Olsen / Scarlet Witch (Avengers)',
      bio: 'Assistant Professor, Department of CSE-Data Science, actively guiding student technical innovations & hackathons.',
      priorityOrder: 2,
    },
    {
      _id: 'mem_fac_03',
      id: 'mem_fac_03',
      name: 'Ms. Pragati Patil',
      role: 'Faculty Coordinator (InfoTech)',
      category: 'Faculty Coordinators',
      department: 'Information Technology',
      year: 'Faculty',
      email: 'pragati.patil@vcet.edu.in',
      phone: '+91 9769990253',
      imageUrl: '/actors/scarlett.jpg',
      starAvatar: 'Scarlett Johansson / Black Widow (Avengers)',
      bio: 'Assistant Professor, Department of Information Technology, mentor for student chapter operations and workshops.',
      priorityOrder: 3,
    },

    // CSI Committee 2025-26 (Bollywood & Avengers Star Avatars)
    {
      _id: 'mem_stu_01',
      id: 'mem_stu_01',
      name: 'Siddharth Chakravarty',
      role: 'Chairperson',
      category: 'Core Council',
      department: 'CSE(DS)',
      year: 'BE',
      email: 'siddharth.c@vcet.edu.in',
      imageUrl: '/actors/rdj.jpg',
      starAvatar: 'Robert Downey Jr. / Iron Man (Avengers)',
      bio: 'Executive Chairperson of CSI VCET Chapter (2025-26), leading technical initiatives and student governance.',
      priorityOrder: 4,
    },
    {
      _id: 'mem_stu_02',
      id: 'mem_stu_02',
      name: 'Aditya Bawane',
      role: 'Treasurer',
      category: 'Core Council',
      department: 'IT',
      year: 'TE',
      email: 'aditya.bawane@vcet.edu.in',
      imageUrl: '/actors/cumberbatch.jpg',
      starAvatar: 'Benedict Cumberbatch / Dr. Strange (Avengers)',
      bio: 'Oversees chapter budgeting, event sponsorships, and institutional accounts.',
      priorityOrder: 5,
    },
    {
      _id: 'mem_stu_03',
      id: 'mem_stu_03',
      name: 'Pranay Ippakayal',
      role: 'Secretary',
      category: 'Core Council',
      department: 'IT',
      year: 'TE',
      email: 'pranay.ippakayal@vcet.edu.in',
      imageUrl: '/actors/srk.jpg',
      starAvatar: 'Shah Rukh Khan (Bollywood)',
      bio: 'Joint Secretary managing documentation, collegiate communication, and official records.',
      priorityOrder: 6,
    },
    {
      _id: 'mem_stu_04',
      id: 'mem_stu_04',
      name: 'Sangini Shetty',
      role: 'Secretary',
      category: 'Core Council',
      department: 'IT',
      year: 'TE',
      email: 'sangini.shetty@vcet.edu.in',
      imageUrl: '/actors/alia.jpg',
      starAvatar: 'Alia Bhatt (Bollywood)',
      bio: 'Managing chapter communications, university records, and annual activity reports.',
      priorityOrder: 7,
    },
    {
      _id: 'mem_stu_05',
      id: 'mem_stu_05',
      name: 'Vatsal Makadiya',
      role: 'Joint Secretary',
      category: 'Core Council',
      department: 'COMPS',
      year: 'SE',
      email: 'vatsal.makadiya@vcet.edu.in',
      imageUrl: '/actors/chrisevans.jpg',
      starAvatar: 'Chris Evans / Captain America (Avengers)',
      bio: 'Department representative and operations coordinator for Computer Engineering.',
      priorityOrder: 8,
    },
    {
      _id: 'mem_stu_06',
      id: 'mem_stu_06',
      name: 'Sumit Mali',
      role: 'Joint Secretary',
      category: 'Core Council',
      department: 'COMPS',
      year: 'SE',
      email: 'sumit.mali@vcet.edu.in',
      imageUrl: '/actors/hemsworth.jpg',
      starAvatar: 'Chris Hemsworth / Thor (Avengers)',
      bio: 'Coordinating internal meetings and inter-departmental student communication.',
      priorityOrder: 9,
    },
    {
      _id: 'mem_stu_07',
      id: 'mem_stu_07',
      name: 'Wajiha Kulsum',
      role: 'Technical Head',
      category: 'Technical Team',
      department: 'COMPS',
      year: 'TE',
      email: 'wajiha.kulsum@vcet.edu.in',
      imageUrl: '/actors/zendaya.jpg',
      starAvatar: 'Zendaya / MJ (Avengers/Marvel)',
      bio: 'Leading technical workshops, web development sessions, and coding competitions.',
      priorityOrder: 10,
    },
    {
      _id: 'mem_stu_08',
      id: 'mem_stu_08',
      name: 'Shubham Singh',
      role: 'Technical Head',
      category: 'Technical Team',
      department: 'IT',
      year: 'TE',
      email: 'shubham.singh@vcet.edu.in',
      imageUrl: '/actors/tomholland.jpg',
      starAvatar: 'Tom Holland / Spider-Man (Avengers)',
      bio: 'Technical architect leading HackVCET development and hands-on coding bootcamps.',
      priorityOrder: 11,
    },
    {
      _id: 'mem_stu_09',
      id: 'mem_stu_09',
      name: 'Parth Vasave',
      role: 'Technical Head',
      category: 'Technical Team',
      department: 'CSE(DS)',
      year: 'TE',
      email: 'parth.vasave@vcet.edu.in',
      imageUrl: '/actors/markruffalo.jpg',
      starAvatar: 'Mark Ruffalo / The Hulk (Avengers)',
      bio: 'Data Science & Systems head organizing AI workshops and algorithmic contests.',
      priorityOrder: 12,
    },
    {
      _id: 'mem_stu_10',
      id: 'mem_stu_10',
      name: 'Shreya Kathe',
      role: 'Organizing Head',
      category: 'Events & Operations',
      department: 'IT',
      year: 'TE',
      email: 'shreya.kathe@vcet.edu.in',
      imageUrl: '/actors/katrina.jpg',
      starAvatar: 'Katrina Kaif (Bollywood)',
      bio: 'Directing stage management, guest welcoming, and overall event schedules.',
      priorityOrder: 13,
    },
    {
      _id: 'mem_stu_11',
      id: 'mem_stu_11',
      name: 'Kunal Patil',
      role: 'Organizing Head',
      category: 'Events & Operations',
      department: 'IT',
      year: 'TE',
      email: 'kunal.patil@vcet.edu.in',
      imageUrl: '/actors/hrithik.jpg',
      starAvatar: 'Hrithik Roshan (Bollywood)',
      bio: 'Oversees venue operations, technical equipment logistics, and student liaison.',
      priorityOrder: 14,
    },
    {
      _id: 'mem_stu_12',
      id: 'mem_stu_12',
      name: 'Aditi Gupta',
      role: 'Organizing Head',
      category: 'Events & Operations',
      department: 'IT',
      year: 'TE',
      email: 'aditi.gupta@vcet.edu.in',
      imageUrl: '/actors/kareena.jpg',
      starAvatar: 'Kareena Kapoor (Bollywood)',
      bio: 'Managing registrations and venue coordination for flagship hackathons.',
      priorityOrder: 15,
    },
    {
      _id: 'mem_stu_13',
      id: 'mem_stu_13',
      name: 'Bhumi Kamble',
      role: 'Organizing Head',
      category: 'Events & Operations',
      department: 'IT',
      year: 'TE',
      email: 'bhumi.kamble@vcet.edu.in',
      imageUrl: '/actors/anushka.jpg',
      starAvatar: 'Anushka Sharma (Bollywood)',
      bio: 'Oversees hospitality, seminar arrangements, and coordinator duties.',
      priorityOrder: 16,
    },
    {
      _id: 'mem_stu_14',
      id: 'mem_stu_14',
      name: 'Aditi Rasal',
      role: 'Organizing Head',
      category: 'Events & Operations',
      department: 'CSE(DS)',
      year: 'SE',
      email: 'aditi.rasal@vcet.edu.in',
      imageUrl: '/actors/deepika.jpg',
      starAvatar: 'Deepika Padukone (Bollywood)',
      bio: 'Coordinating event flow and student volunteer teams.',
      priorityOrder: 17,
    },
    {
      _id: 'mem_stu_15',
      id: 'mem_stu_15',
      name: 'Meenakshi Kshirsagar',
      role: 'PR Head',
      category: 'Creatives & PR',
      department: 'IT',
      year: 'TE',
      email: 'meenakshi.k@vcet.edu.in',
      imageUrl: '/actors/elizabeth_olsen.jpg',
      starAvatar: 'Elizabeth Olsen / Wanda (Avengers)',
      bio: 'Public relations and external communication strategist.',
      priorityOrder: 18,
    },
    {
      _id: 'mem_stu_16',
      id: 'mem_stu_16',
      name: 'Khushi Machhi',
      role: 'PR Head',
      category: 'Creatives & PR',
      department: 'IT',
      year: 'TE',
      email: 'khushi.machhi@vcet.edu.in',
      imageUrl: '/actors/scarlett.jpg',
      starAvatar: 'Scarlett Johansson / Black Widow (Avengers)',
      bio: 'Overseeing social media presence, student announcements, and outreach.',
      priorityOrder: 19,
    },
    {
      _id: 'mem_stu_17',
      id: 'mem_stu_17',
      name: 'Shardul Brid',
      role: 'PR Head',
      category: 'Creatives & PR',
      department: 'CSE(DS)',
      year: 'TE',
      email: 'shardul.brid@vcet.edu.in',
      imageUrl: '/actors/ranveer.jpg',
      starAvatar: 'Ranveer Singh (Bollywood)',
      bio: 'Digital marketing and media liaison across engineering departments.',
      priorityOrder: 20,
    },
    {
      _id: 'mem_stu_18',
      id: 'mem_stu_18',
      name: 'Gargi Betawadkar',
      role: 'Admin Head',
      category: 'Core Council',
      department: 'COMPS',
      year: 'TE',
      email: 'gargi.b@vcet.edu.in',
      imageUrl: '/actors/alia.jpg',
      starAvatar: 'Alia Bhatt (Bollywood)',
      bio: 'Administering council records, membership approvals, and regulatory compliances.',
      priorityOrder: 21,
    },
    {
      _id: 'mem_stu_19',
      id: 'mem_stu_19',
      name: 'Shreya Dadhekar',
      role: 'Admin Head',
      category: 'Core Council',
      department: 'CSE(DS)',
      year: 'TE',
      email: 'shreya.d@vcet.edu.in',
      imageUrl: '/actors/zendaya.jpg',
      starAvatar: 'Zendaya (Avengers / Marvel)',
      bio: 'Managing chapter schedules, logistics rosters, and internal administration.',
      priorityOrder: 22,
    },
    {
      _id: 'mem_stu_20',
      id: 'mem_stu_20',
      name: 'Saivamehi Jilla',
      role: 'Admin Head',
      category: 'Core Council',
      department: 'COMPS',
      year: 'TE',
      email: 'saivamehi.j@vcet.edu.in',
      imageUrl: '/actors/katrina.jpg',
      starAvatar: 'Katrina Kaif (Bollywood)',
      bio: 'Coordinating formal university correspondence and student records.',
      priorityOrder: 23,
    },
    // Distinguished Patrons & Advisors
    {
      _id: 'mem_pat_01',
      id: 'mem_pat_01',
      name: 'Dr. Harish V. Narang (Patron)',
      role: 'Principal & Chapter Patron',
      category: 'Faculty Coordinators',
      department: 'Administration',
      year: 'Principal',
      email: 'principal@vcet.edu.in',
      imageUrl: '/actors/amitabh.jpg',
      starAvatar: 'Amitabh Bachchan (Bollywood Legend)',
      bio: 'Principal of Vidyavardhini\'s College of Engineering and Technology, Chief Institutional Patron.',
      priorityOrder: 0,
    },
    {
      _id: 'mem_adv_01',
      id: 'mem_adv_01',
      name: 'Prof. Rajesh K. Bansode',
      role: 'Head of Computer Engineering',
      category: 'Faculty Coordinators',
      department: 'Computer Engineering',
      year: 'HOD',
      email: 'hod.comps@vcet.edu.in',
      imageUrl: '/actors/salman.jpg',
      starAvatar: 'Salman Khan (Bollywood)',
      bio: 'Head of Department, Computer Engineering, mentoring student innovations and academic-industry alignment.',
      priorityOrder: 0,
    },
    {
      _id: 'mem_adv_02',
      id: 'mem_adv_02',
      name: 'Prof. Santosh Tambe',
      role: 'Head of Information Technology',
      category: 'Faculty Coordinators',
      department: 'Information Technology',
      year: 'HOD',
      email: 'hod.it@vcet.edu.in',
      imageUrl: '/actors/aamir.jpg',
      starAvatar: 'Aamir Khan (Bollywood)',
      bio: 'Head of Department, Information Technology, championing hackathons and open-source contributions.',
      priorityOrder: 0,
    },
  ],
  events: [
    {
      _id: 'ev_001',
      id: 'ev_001',
      title: 'HackVCET 2026: 36-Hour National Hackathon',
      subtitle: 'Igniting Technological Solutions for Real-World Problems',
      description: 'VCET’s flagship hackathon in association with CSI India. Over ₹1,00,000 in cash prizes, mentors from top tech companies, and tracks covering AI/ML, Web3, FinTech, and Smart Automation.',
      category: 'Hackathon',
      date: new Date('2026-11-14T09:00:00Z'),
      time: '09:00 AM - Next Day 09:00 PM IST',
      venue: 'VCET Main Auditorium & Advanced Computing Labs, Vasai',
      imageUrl: 'https://images.unsplash.com/photo-1504384308090-c894fdcc538d?w=800&auto=format&fit=crop&q=80',
      registrationUrl: '#apply',
      status: 'Upcoming',
      speakers: ['Tech Mentors from Google', 'AWS Community Builders'],
      seatsTotal: 250,
      seatsFilled: 198,
    },
    {
      _id: 'ev_002',
      id: 'ev_002',
      title: 'Full-Stack MERN Mastery Bootcamp',
      subtitle: 'Hands-on project building with React, Node, Express & MongoDB',
      description: 'An intensive two-day hands-on workshop guiding students through REST API design, JWT authentication, state management, and modern cloud deployment pipelines.',
      category: 'Workshop',
      date: new Date('2026-10-25T10:00:00Z'),
      time: '10:00 AM - 04:30 PM IST',
      venue: 'Lab 402, Department of Computer Engineering, VCET',
      imageUrl: 'https://images.unsplash.com/photo-1517694712202-14dd9538aa97?w=800&auto=format&fit=crop&q=80',
      registrationUrl: '#apply',
      status: 'Upcoming',
      speakers: ['CSI VCET Senior Core Developers'],
      seatsTotal: 80,
      seatsFilled: 68,
    },
    {
      _id: 'ev_003',
      id: 'ev_003',
      title: 'Demystifying Generative AI & LLM Systems',
      subtitle: 'Expert Seminar on RAG, Agents, and Production AI Architecture',
      description: 'Distinguished guest lecture featuring industry AI architects detailing the evolution of LLMs, embedding search, vector databases, and real-world enterprise adoption.',
      category: 'Technical Seminar',
      date: new Date('2026-10-18T11:00:00Z'),
      time: '11:00 AM - 01:30 PM IST',
      venue: 'Seminar Hall 1, VCET Campus',
      imageUrl: 'https://images.unsplash.com/photo-1618005182384-a83a8bd57fbe?w=800&auto=format&fit=crop&q=80',
      registrationUrl: '#apply',
      status: 'Upcoming',
      speakers: ['Industry AI Staff Engineer'],
      seatsTotal: 150,
      seatsFilled: 135,
    },
    {
      _id: 'ev_004',
      id: 'ev_004',
      title: 'CodeSprint: Intra-College Algorithmic Challenge',
      subtitle: 'Fast-paced algorithmic problem-solving sprint',
      description: 'Annual competitive programming contest hosted on HackerEarth. Tests data structures, algorithms, and rapid problem-solving skills across all engineering departments.',
      category: 'Coding Contest',
      date: new Date('2026-09-20T14:00:00Z'),
      time: '02:00 PM - 05:00 PM IST',
      venue: 'VCET Cloud Labs',
      imageUrl: 'https://images.unsplash.com/photo-1526374965328-7f61d4dc18c5?w=800&auto=format&fit=crop&q=80',
      registrationUrl: '#apply',
      status: 'Completed',
      speakers: ['CSI Coding Council'],
      seatsTotal: 100,
      seatsFilled: 100,
    },
  ],
};

// Initialize in-memory admin password hash
export const initInMemoryPasswords = async () => {
  if (inMemoryStore.users[0] && !inMemoryStore.users[0].password) {
    const salt = await bcrypt.genSalt(10);
    inMemoryStore.users[0].password = await bcrypt.hash(inMemoryStore.users[0].plainPassword, salt);
  }
};

// Seed MongoDB if connected
export const seedDatabase = async () => {
  await initInMemoryPasswords();
  const { connected } = getDbStatus();
  if (!connected) {
    console.log('[Seeder] In-memory store ready with sample CSI VCET data.');
    return;
  }

  try {
    const userCount = await User.countDocuments();
    if (userCount === 0) {
      console.log('[Seeder] Seeding default Admin user into MongoDB...');
      for (const u of inMemoryStore.users) {
        await User.create({
          name: u.name,
          email: u.email,
          password: u.plainPassword,
          role: u.role,
          chapterDesignation: u.chapterDesignation,
        });
      }
    }

    const appCount = await Application.countDocuments();
    if (appCount === 0) {
      console.log('[Seeder] Seeding initial student applications into MongoDB...');
      for (const a of inMemoryStore.applications) {
        const { _id, id, ...rest } = a;
        await Application.create(rest);
      }
    }

    const memberCount = await Member.countDocuments();
    if (memberCount === 0) {
      console.log('[Seeder] Seeding chapter council members into MongoDB...');
      for (const m of inMemoryStore.members) {
        const { _id, id, ...rest } = m;
        await Member.create(rest);
      }
    }

    const eventCount = await Event.countDocuments();
    if (eventCount === 0) {
      console.log('[Seeder] Seeding flagship events into MongoDB...');
      for (const e of inMemoryStore.events) {
        const { _id, id, ...rest } = e;
        await Event.create(rest);
      }
    }

    console.log('[Seeder] Database initialized successfully!');
  } catch (error) {
    console.error('[Seeder Error]', error.message);
  }
};
